// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: acl.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getGroupByName = `-- name: GetGroupByName :one
SELECT id, name, description, is_system, created_at, updated_at FROM groups WHERE name = $1
`

func (q *Queries) GetGroupByName(ctx context.Context, name string) (Group, error) {
	row := q.db.QueryRow(ctx, getGroupByName, name)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPermissionByName = `-- name: GetPermissionByName :one
SELECT id, name, subject, action, description, created_at, updated_at FROM permissions WHERE name = $1
`

func (q *Queries) GetPermissionByName(ctx context.Context, name string) (Permission, error) {
	row := q.db.QueryRow(ctx, getPermissionByName, name)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Subject,
		&i.Action,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const joinUserToGroup = `-- name: JoinUserToGroup :exec
INSERT INTO group_user (group_id, user_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type JoinUserToGroupParams struct {
	GroupID uuid.UUID `json:"group_id"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) JoinUserToGroup(ctx context.Context, arg JoinUserToGroupParams) error {
	_, err := q.db.Exec(ctx, joinUserToGroup, arg.GroupID, arg.UserID)
	return err
}

const linkGroupPermission = `-- name: LinkGroupPermission :exec
INSERT INTO group_permission (group_id, permission_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type LinkGroupPermissionParams struct {
	GroupID      uuid.UUID `json:"group_id"`
	PermissionID uuid.UUID `json:"permission_id"`
}

func (q *Queries) LinkGroupPermission(ctx context.Context, arg LinkGroupPermissionParams) error {
	_, err := q.db.Exec(ctx, linkGroupPermission, arg.GroupID, arg.PermissionID)
	return err
}

const listGroupsForUser = `-- name: ListGroupsForUser :many
SELECT g.id, g.name, g.description, g.is_system, g.created_at, g.updated_at
FROM groups g
JOIN group_user gu ON gu.group_id = g.id
WHERE gu.user_id = $1
ORDER BY g.name
`

func (q *Queries) ListGroupsForUser(ctx context.Context, userID uuid.UUID) ([]Group, error) {
	rows, err := q.db.Query(ctx, listGroupsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Group{}
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsSystem,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionsForGroup = `-- name: ListPermissionsForGroup :many
SELECT p.id, p.name, p.subject, p.action, p.description, p.created_at, p.updated_at
FROM permissions p
JOIN group_permission gp ON gp.permission_id = p.id
WHERE gp.group_id = $1
ORDER BY p.name
`

func (q *Queries) ListPermissionsForGroup(ctx context.Context, groupID uuid.UUID) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listPermissionsForGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Subject,
			&i.Action,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionsForUser = `-- name: ListPermissionsForUser :many
SELECT DISTINCT p.id, p.name, p.subject, p.action, p.description, p.created_at, p.updated_at
FROM permissions p
JOIN group_permission gp ON gp.permission_id = p.id
JOIN group_user       gu ON gu.group_id      = gp.group_id
WHERE gu.user_id = $1
ORDER BY p.name
`

func (q *Queries) ListPermissionsForUser(ctx context.Context, userID uuid.UUID) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listPermissionsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Subject,
			&i.Action,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeUserFromGroup = `-- name: RemoveUserFromGroup :exec
DELETE FROM group_user
WHERE group_id = $1 AND user_id = $2
`

type RemoveUserFromGroupParams struct {
	GroupID uuid.UUID `json:"group_id"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveUserFromGroup(ctx context.Context, arg RemoveUserFromGroupParams) error {
	_, err := q.db.Exec(ctx, removeUserFromGroup, arg.GroupID, arg.UserID)
	return err
}

const unlinkGroupPermission = `-- name: UnlinkGroupPermission :exec
DELETE FROM group_permission
WHERE group_id = $1 AND permission_id = $2
`

type UnlinkGroupPermissionParams struct {
	GroupID      uuid.UUID `json:"group_id"`
	PermissionID uuid.UUID `json:"permission_id"`
}

func (q *Queries) UnlinkGroupPermission(ctx context.Context, arg UnlinkGroupPermissionParams) error {
	_, err := q.db.Exec(ctx, unlinkGroupPermission, arg.GroupID, arg.PermissionID)
	return err
}

const upsertGroup = `-- name: UpsertGroup :one
INSERT INTO groups (name, description, is_system)
VALUES ($1, $2, $3)
ON CONFLICT (name) DO UPDATE
SET description = EXCLUDED.description,
    is_system   = EXCLUDED.is_system,
    updated_at  = NOW()
RETURNING id, name, description, is_system, created_at, updated_at
`

type UpsertGroupParams struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
	IsSystem    bool    `json:"is_system"`
}

func (q *Queries) UpsertGroup(ctx context.Context, arg UpsertGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, upsertGroup, arg.Name, arg.Description, arg.IsSystem)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPermission = `-- name: UpsertPermission :one
INSERT INTO permissions (name, subject, action, description)
VALUES ($1, $2, $3, $4)
ON CONFLICT (name) DO UPDATE
SET subject     = EXCLUDED.subject,
    action      = EXCLUDED.action,
    description = EXCLUDED.description,
    updated_at  = NOW()
RETURNING id, name, subject, action, description, created_at, updated_at
`

type UpsertPermissionParams struct {
	Name        string  `json:"name"`
	Subject     string  `json:"subject"`
	Action      string  `json:"action"`
	Description *string `json:"description"`
}

func (q *Queries) UpsertPermission(ctx context.Context, arg UpsertPermissionParams) (Permission, error) {
	row := q.db.QueryRow(ctx, upsertPermission,
		arg.Name,
		arg.Subject,
		arg.Action,
		arg.Description,
	)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Subject,
		&i.Action,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
