// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const listAuditLog = `-- name: ListAuditLog :many
SELECT id, actor_user_id, actor_kind, action, subject_type, subject_id, changes, created_at, COUNT(*) OVER() AS total
FROM audit_log
WHERE ($3::UUID IS NULL OR actor_user_id = $3)
  AND ($4::TEXT IS NULL OR subject_type = $4)
  AND ($5::UUID   IS NULL OR subject_id   = $5)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAuditLogParams struct {
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
	ActorUserID pgtype.UUID `json:"actor_user_id"`
	SubjectType *string     `json:"subject_type"`
	SubjectID   pgtype.UUID `json:"subject_id"`
}

type ListAuditLogRow struct {
	ID          uuid.UUID   `json:"id"`
	ActorUserID pgtype.UUID `json:"actor_user_id"`
	ActorKind   string      `json:"actor_kind"`
	Action      string      `json:"action"`
	SubjectType string      `json:"subject_type"`
	SubjectID   pgtype.UUID `json:"subject_id"`
	Changes     []byte      `json:"changes"`
	CreatedAt   time.Time   `json:"created_at"`
	Total       int64       `json:"total"`
}

// Paginated list with total via COUNT(*) OVER(). Ordered newest-first.
// Filters are optional via sqlc.narg so the same query supports
// "all", "by actor", "by subject", or "by subject_type" lookups.
func (q *Queries) ListAuditLog(ctx context.Context, arg ListAuditLogParams) ([]ListAuditLogRow, error) {
	rows, err := q.db.Query(ctx, listAuditLog,
		arg.Limit,
		arg.Offset,
		arg.ActorUserID,
		arg.SubjectType,
		arg.SubjectID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditLogRow{}
	for rows.Next() {
		var i ListAuditLogRow
		if err := rows.Scan(
			&i.ID,
			&i.ActorUserID,
			&i.ActorKind,
			&i.Action,
			&i.SubjectType,
			&i.SubjectID,
			&i.Changes,
			&i.CreatedAt,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordAuditLog = `-- name: RecordAuditLog :one
INSERT INTO audit_log (actor_user_id, actor_kind, action, subject_type, subject_id, changes)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, actor_user_id, actor_kind, action, subject_type, subject_id, changes, created_at
`

type RecordAuditLogParams struct {
	ActorUserID pgtype.UUID `json:"actor_user_id"`
	ActorKind   string      `json:"actor_kind"`
	Action      string      `json:"action"`
	SubjectType string      `json:"subject_type"`
	SubjectID   pgtype.UUID `json:"subject_id"`
	Changes     []byte      `json:"changes"`
}

func (q *Queries) RecordAuditLog(ctx context.Context, arg RecordAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, recordAuditLog,
		arg.ActorUserID,
		arg.ActorKind,
		arg.Action,
		arg.SubjectType,
		arg.SubjectID,
		arg.Changes,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.ActorUserID,
		&i.ActorKind,
		&i.Action,
		&i.SubjectType,
		&i.SubjectID,
		&i.Changes,
		&i.CreatedAt,
	)
	return i, err
}
