// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: login_attempts.sql

package sqlc

import (
	"context"
	"net/netip"
	"time"
)

const countRecentFailedLogins = `-- name: CountRecentFailedLogins :one
SELECT COUNT(*)::INT AS failures
FROM login_attempts
WHERE email = $1
  AND succeeded = FALSE
  AND created_at >= $2
`

type CountRecentFailedLoginsParams struct {
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
}

// Drives the ACC-6 lockout: caller passes the cutoff (NOW() - window).
func (q *Queries) CountRecentFailedLogins(ctx context.Context, arg CountRecentFailedLoginsParams) (int32, error) {
	row := q.db.QueryRow(ctx, countRecentFailedLogins, arg.Email, arg.CreatedAt)
	var failures int32
	err := row.Scan(&failures)
	return failures, err
}

const deleteOldLoginAttempts = `-- name: DeleteOldLoginAttempts :exec
DELETE FROM login_attempts WHERE created_at < NOW() - INTERVAL '30 days'
`

// Keeps the table from growing unboundedly. Cron-driven; safe to run any time.
func (q *Queries) DeleteOldLoginAttempts(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteOldLoginAttempts)
	return err
}

const recordLoginAttempt = `-- name: RecordLoginAttempt :exec
INSERT INTO login_attempts (email, ip, succeeded)
VALUES ($1, $2, $3)
`

type RecordLoginAttemptParams struct {
	Email     string      `json:"email"`
	Ip        *netip.Addr `json:"ip"`
	Succeeded bool        `json:"succeeded"`
}

func (q *Queries) RecordLoginAttempt(ctx context.Context, arg RecordLoginAttemptParams) error {
	_, err := q.db.Exec(ctx, recordLoginAttempt, arg.Email, arg.Ip, arg.Succeeded)
	return err
}
