// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CancelUserDeletionGrace(ctx context.Context, id uuid.UUID) error
	ConsumeEmailVerificationToken(ctx context.Context, id uuid.UUID) error
	ConsumePasswordResetToken(ctx context.Context, id uuid.UUID) error
	// Drives the ACC-6 lockout: caller passes the cutoff (NOW() - window).
	CountRecentFailedLogins(ctx context.Context, arg CountRecentFailedLoginsParams) (int32, error)
	CreateEmailVerificationToken(ctx context.Context, arg CreateEmailVerificationTokenParams) (EmailVerificationToken, error)
	CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error)
	CreateRefreshSession(ctx context.Context, arg CreateRefreshSessionParams) (RefreshSession, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteExpiredEmailVerificationTokens(ctx context.Context) error
	DeleteExpiredPasswordResetTokens(ctx context.Context) error
	DeleteExpiredRefreshSessions(ctx context.Context) error
	// Keeps the table from growing unboundedly. Cron-driven; safe to run any time.
	DeleteOldLoginAttempts(ctx context.Context) error
	GetEmailVerificationToken(ctx context.Context, tokenHash string) (EmailVerificationToken, error)
	GetGroupByName(ctx context.Context, name string) (Group, error)
	GetPasswordResetToken(ctx context.Context, tokenHash string) (PasswordResetToken, error)
	GetPermissionByName(ctx context.Context, name string) (Permission, error)
	GetRefreshSessionByTokenHash(ctx context.Context, tokenHash string) (RefreshSession, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	IsEmailVerified(ctx context.Context, id uuid.UUID) (bool, error)
	JoinUserToGroup(ctx context.Context, arg JoinUserToGroupParams) error
	LinkGroupPermission(ctx context.Context, arg LinkGroupPermissionParams) error
	ListGroupsForUser(ctx context.Context, userID uuid.UUID) ([]Group, error)
	ListPermissionsForGroup(ctx context.Context, groupID uuid.UUID) ([]Permission, error)
	ListPermissionsForUser(ctx context.Context, userID uuid.UUID) ([]Permission, error)
	MarkUserEmailVerified(ctx context.Context, id uuid.UUID) error
	RecordLoginAttempt(ctx context.Context, arg RecordLoginAttemptParams) error
	RemoveUserFromGroup(ctx context.Context, arg RemoveUserFromGroupParams) error
	RevokeAllRefreshSessionsForUser(ctx context.Context, userID uuid.UUID) error
	RevokeOtherRefreshSessionsForUser(ctx context.Context, arg RevokeOtherRefreshSessionsForUserParams) error
	RevokeRefreshSession(ctx context.Context, id uuid.UUID) error
	SetUserDisabled(ctx context.Context, arg SetUserDisabledParams) error
	StartUserDeletionGrace(ctx context.Context, id uuid.UUID) error
	TouchRefreshSession(ctx context.Context, id uuid.UUID) error
	UnlinkGroupPermission(ctx context.Context, arg UnlinkGroupPermissionParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	UpsertGroup(ctx context.Context, arg UpsertGroupParams) (Group, error)
	UpsertPermission(ctx context.Context, arg UpsertPermissionParams) (Permission, error)
}

var _ Querier = (*Queries)(nil)
