// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlc

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const createRefreshSession = `-- name: CreateRefreshSession :one
INSERT INTO refresh_sessions (user_id, token_hash, user_agent, ip, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, token_hash, user_agent, ip, expires_at, revoked_at, last_used_at, created_at
`

type CreateRefreshSessionParams struct {
	UserID    uuid.UUID   `json:"user_id"`
	TokenHash string      `json:"token_hash"`
	UserAgent *string     `json:"user_agent"`
	Ip        *netip.Addr `json:"ip"`
	ExpiresAt time.Time   `json:"expires_at"`
}

func (q *Queries) CreateRefreshSession(ctx context.Context, arg CreateRefreshSessionParams) (RefreshSession, error) {
	row := q.db.QueryRow(ctx, createRefreshSession,
		arg.UserID,
		arg.TokenHash,
		arg.UserAgent,
		arg.Ip,
		arg.ExpiresAt,
	)
	var i RefreshSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.UserAgent,
		&i.Ip,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredRefreshSessions = `-- name: DeleteExpiredRefreshSessions :exec
DELETE FROM refresh_sessions
WHERE expires_at < NOW() OR (revoked_at IS NOT NULL AND revoked_at < NOW() - INTERVAL '7 days')
`

func (q *Queries) DeleteExpiredRefreshSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredRefreshSessions)
	return err
}

const getRefreshSessionByTokenHash = `-- name: GetRefreshSessionByTokenHash :one
SELECT id, user_id, token_hash, user_agent, ip, expires_at, revoked_at, last_used_at, created_at FROM refresh_sessions
WHERE token_hash = $1
  AND revoked_at IS NULL
  AND expires_at > NOW()
`

func (q *Queries) GetRefreshSessionByTokenHash(ctx context.Context, tokenHash string) (RefreshSession, error) {
	row := q.db.QueryRow(ctx, getRefreshSessionByTokenHash, tokenHash)
	var i RefreshSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.UserAgent,
		&i.Ip,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const revokeAllRefreshSessionsForUser = `-- name: RevokeAllRefreshSessionsForUser :exec
UPDATE refresh_sessions
SET revoked_at = NOW()
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllRefreshSessionsForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllRefreshSessionsForUser, userID)
	return err
}

const revokeOtherRefreshSessionsForUser = `-- name: RevokeOtherRefreshSessionsForUser :exec
UPDATE refresh_sessions
SET revoked_at = NOW()
WHERE user_id = $1 AND id <> $2 AND revoked_at IS NULL
`

type RevokeOtherRefreshSessionsForUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) RevokeOtherRefreshSessionsForUser(ctx context.Context, arg RevokeOtherRefreshSessionsForUserParams) error {
	_, err := q.db.Exec(ctx, revokeOtherRefreshSessionsForUser, arg.UserID, arg.ID)
	return err
}

const revokeRefreshSession = `-- name: RevokeRefreshSession :exec
UPDATE refresh_sessions
SET revoked_at = NOW()
WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshSession, id)
	return err
}

const touchRefreshSession = `-- name: TouchRefreshSession :exec
UPDATE refresh_sessions
SET last_used_at = NOW()
WHERE id = $1
`

func (q *Queries) TouchRefreshSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchRefreshSession, id)
	return err
}
