// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelUserDeletionGrace = `-- name: CancelUserDeletionGrace :exec
UPDATE users
SET deletion_requested_at = NULL,
    updated_at            = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) CancelUserDeletionGrace(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, cancelUserDeletionGrace, id)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, name, password_hash)
VALUES ($1, $2, $3)
RETURNING id, email, name, password_hash, avatar_url, email_verified_at, is_disabled, deletion_requested_at, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	Name         string `json:"name"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Name, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.EmailVerifiedAt,
		&i.IsDisabled,
		&i.DeletionRequestedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, password_hash, avatar_url, email_verified_at, is_disabled, deletion_requested_at, created_at, updated_at, deleted_at FROM users WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.EmailVerifiedAt,
		&i.IsDisabled,
		&i.DeletionRequestedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, password_hash, avatar_url, email_verified_at, is_disabled, deletion_requested_at, created_at, updated_at, deleted_at FROM users WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.EmailVerifiedAt,
		&i.IsDisabled,
		&i.DeletionRequestedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const isEmailVerified = `-- name: IsEmailVerified :one
SELECT (email_verified_at IS NOT NULL)::BOOLEAN AS verified
FROM users
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) IsEmailVerified(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isEmailVerified, id)
	var verified bool
	err := row.Scan(&verified)
	return verified, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, name, email_verified_at, is_disabled, created_at,
       COUNT(*) OVER() AS total
FROM users
WHERE deleted_at IS NULL
  AND ($3::TEXT IS NULL
       OR email ILIKE '%' || $3::TEXT || '%')
ORDER BY email
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit     int32   `json:"limit"`
	Offset    int32   `json:"offset"`
	EmailLike *string `json:"email_like"`
}

type ListUsersRow struct {
	ID              uuid.UUID          `json:"id"`
	Email           string             `json:"email"`
	Name            string             `json:"name"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	IsDisabled      bool               `json:"is_disabled"`
	CreatedAt       time.Time          `json:"created_at"`
	Total           int64              `json:"total"`
}

// Admin user-listing. Optional case-insensitive substring filter on
// email; nil = no filter. Excludes soft-deleted users.
func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset, arg.EmailLike)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.EmailVerifiedAt,
			&i.IsDisabled,
			&i.CreatedAt,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markUserEmailVerified = `-- name: MarkUserEmailVerified :exec
UPDATE users
SET email_verified_at = COALESCE(email_verified_at, NOW()),
    updated_at        = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) MarkUserEmailVerified(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markUserEmailVerified, id)
	return err
}

const setUserDisabled = `-- name: SetUserDisabled :exec
UPDATE users
SET is_disabled = $2,
    updated_at  = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

type SetUserDisabledParams struct {
	ID         uuid.UUID `json:"id"`
	IsDisabled bool      `json:"is_disabled"`
}

func (q *Queries) SetUserDisabled(ctx context.Context, arg SetUserDisabledParams) error {
	_, err := q.db.Exec(ctx, setUserDisabled, arg.ID, arg.IsDisabled)
	return err
}

const startUserDeletionGrace = `-- name: StartUserDeletionGrace :exec
UPDATE users
SET deletion_requested_at = NOW(),
    updated_at            = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) StartUserDeletionGrace(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, startUserDeletionGrace, id)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $2,
    updated_at    = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET name       = COALESCE($1,       name),
    avatar_url = COALESCE($2, avatar_url),
    updated_at = NOW()
WHERE id = $3 AND deleted_at IS NULL
RETURNING id, email, name, password_hash, avatar_url, email_verified_at, is_disabled, deletion_requested_at, created_at, updated_at, deleted_at
`

type UpdateUserProfileParams struct {
	Name      *string   `json:"name"`
	AvatarUrl *string   `json:"avatar_url"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile, arg.Name, arg.AvatarUrl, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.EmailVerifiedAt,
		&i.IsDisabled,
		&i.DeletionRequestedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
