root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/qp ./cmd/qp"
bin = "./tmp/qp"
args_bin = ["serve:api"]
include_ext = ["go"]
include_dir = ["cmd/qp", "internal"]
exclude_dir = ["tmp", "bin", "migrations", ".git"]
delay = 200
stop_on_error = true
send_interrupt = true
kill_delay = "2s"

[log]
time = true

[misc]
clean_on_exit = true
